[workspace]
members = [
    "bip32",
    "bip39",
    "cbor-util",
    "database",
    "kes",
    "ledger",
    # "network",
    "plutus",
    "state",
]
resolver = "3"

# TODO: Figure out features to enable for each dep.
[workspace.dependencies]

# Async
tokio = "1.50.0"
tokio-stream = { version = "0.1.18", default-features = false }

# CBOR
cbor-util = { path = "cbor-util" }
embedded-io = "0.7.1"
tinycbor = "0.14.0"
tinycbor-derive = "0.15.4"

# Crypto Traits
digest = { version = "0.11.0", default-features = false }
signature = { version = "3.0.0", default-features = false }

# Data types
hashbrown = { version = "0.17", default-features = false, features = [
    "inline-more",
] }
mitsein = "0.9"
rug = { version = "1.28.0", default-features = false, features = [
    "integer",
    "std",
] }

# Hashing
blake2 = { version = "0.11.0-rc.5", default-features = false }
crc32fast = "1.5"
sha2 = { version = "0.11.0", default-features = false }
sha3 = { version = "0.12.0", default-features = false }

# Public Key Cryptography
curve25519-dalek = { version = "5.0.0", default-features = false }
ed25519-dalek = { version = "3.0.0", default-features = false }
# FIXME: remove once ed25519-dalek has a zerocopy feature also that enables this
ed25519 = { version = "3.0.0", features = ["zerocopy"] }
hybrid-array = { version = "0.4.12" }

# Utilities
bytes = "1.11.1"
const-hex = { version = "1" }
displaydoc = "0.2"
macro_rules_attribute = "0.2.2"
rand = "0.10"
ref-cast = "1.0"
thiserror = "2.0"
yoke = { version = "0.8.3", default-features = false, features = [
    "alloc",
    "derive",
] }
zerocopy = { version = "0.8", features = ["derive"] }

# FIXME: Remove once https://github.com/olson-sean-k/mitsein/pull/56 is merged.
[patch.crates-io]
mitsein = { git = "https://github.com/carloskiki/mitsein", branch = "unsized-clone" }
