[package]
name = "sparse-struct"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[[test]]
name = "ui"
path = "tests/ui.rs"

[dev-dependencies]
trybuild = { version = "1.0.110", features = ["diff"] }

[dependencies]
proc-macro2 = "1.0.95"
syn = "2.0.104"
quote = "1.0.40"
heck = "0.5.0"
