//! Transaction and its components.
//!
//! A transaction spends unspent transaction outputs (UTXOs) and generates new UTXOs. The UTXOs to
//! be spent are [`inputs`](Transaction::inputs) and the new UTXOs generated are
//! [`ouputs`](Transaction::outputs).

use mitsein::boxed1::BoxedSlice1;
use tinycbor_derive::{CborLen, Decode, Encode};

mod output;
pub use output::Output;

mod payload;
pub use payload::Payload;

mod proof;
pub use proof::Proof;

pub mod witness;
pub use witness::Witness;

/// A transaction.
///
/// Spends the provided `inputs` and generates new `outputs`. The fee paid is defined implicitly as
/// the difference between the total amounts in the `inputs` and the total generated in the
/// `outputs`.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Encode, Decode, CborLen)]
pub struct Transaction {
    /// The unspent transaction outputs to be used as inputs for this transaction.
    #[cbor(with = "crate::transaction::reference::codec::ByronReferences")]
    pub inputs: BoxedSlice1<crate::transaction::Reference>,
    /// The new outputs generated by this transaction.
    #[cbor(with = "cbor_util::NonEmpty<Output>")]
    pub outputs: BoxedSlice1<Output>,
    /// Unused attribute field.
    pub attributes: super::Attributes,
}
