[package]
edition = "2024"
name = "database"
version = "0.1.0"

[dependencies]
once_cell = "1.21.4"
crossbeam-utils = "0.8.21"
tinycbor = { workspace = true }
zerocopy = { workspace = true }
bytes = { workspace = true }
crc32fast = { workspace = true }
blake2 = { workspace = true }

[dev-dependencies]
ledger = { path = "../ledger" }
tempfile = "3.27.0"
sysinfo = { version = "0.39", default-features = false, features = ["system"] }

[[bench]]
harness = false
name = "iterate"
