[package]
edition = "2024"
name = "database"
version = "0.1.0"

[dependencies]
once_cell = "1.21.4"
crossbeam-utils = "0.8.21"
tinycbor = { workspace = true }
zerocopy = { workspace = true }
bytes = { workspace = true }
crc32fast = { workspace = true }
blake2 = { workspace = true }

[dev-dependencies]
ledger = { path = "../ledger" }
libc = "0.2"
tempfile = "3.27.0"

[[bench]]
harness = false
name = "iterate"
